name: CI/CD

on:
  push:
    branches: [ front-end-dev ]
  pull_request:
    branches: [ front-end-dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Checkout repository
      working-directory: ./frontend
    - uses: actions/checkout@v2
      
    - name: Set up Node.js ${{ matrix.node-version }}
      working-directory: ./frontend
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      working-directory: ./frontend
      run: npm install

    - name: Run the tests
      working-directory: ./frontend
      run: npm test

    - name: Build
      working-directory: ./frontend
      run: npm run build
